import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
const API='/api';
function App(){
 const [docs,setDocs]=useState([]),[question,setQuestion]=useState(''),[answer,setAnswer]=useState(null),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[notice,setNotice]=useState('');
 async function reload(){try{const r=await fetch(API+'/documents');if(!r.ok)throw Error('Backend unavailable');setDocs(await r.json())}catch(e){setNotice('Start PostgreSQL and FastAPI: '+e.message)}}
 useEffect(()=>{reload()},[]);
 async function upload(e){const f=e.target.files?.[0];if(!f)return;setUploading(true);setNotice('');const form=new FormData();form.append('file',f);try{const r=await fetch(API+'/documents',{method:'POST',body:form});const d=await r.json();if(!r.ok)throw Error(d.detail||'Upload failed');setNotice('Indexed '+d.filename+' ('+d.chunks+' chunks)');await reload()}catch(e){setNotice(e.message)}finally{setUploading(false);e.target.value=''}}
 async function ask(e){e.preventDefault();if(!question.trim())return;setBusy(true);setAnswer(null);setNotice('');try{const r=await fetch(API+'/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question})});const d=await r.json();if(!r.ok)throw Error(d.detail||'Request failed');setAnswer(d)}catch(e){setNotice(e.message)}finally{setBusy(false)}}
 return <div className="app"><aside><h1>🌿 BhoomiAI</h1><p>Land Research Workspace</p><div className="tag">STAGE 1 · LOCAL RAG</div><h3>Documents ({docs.length})</h3><label className="upload">{uploading?'Indexing...':'Upload PDF / TXT / MD'}<input type="file" accept=".pdf,.txt,.md" disabled={uploading} onChange={upload}/></label>{docs.map(d=><div className="doc" key={d.id}><strong>{d.filename}</strong><small>{d.chunks} chunks</small></div>)}{!docs.length&&<p>No documents yet. Upload the sample file.</p>}<footer>Free local model · Development only</footer></aside><main><header><div className="eyebrow">RESEARCH DISCOVERY</div><h2>Ask your land-governance documents</h2><p>Evidence-grounded answers with retrieved source passages.</p></header><section><form onSubmit={ask}><label htmlFor="question">Your research question</label><textarea id="question" rows={4} value={question} onChange={e=>setQuestion(e.target.value)} placeholder="What issues affect land-record modernization?"/><button disabled={busy||!question.trim()}>{busy?'Searching...':'Ask BhoomiAI'}</button></form>{notice&&<div className="notice">{notice}</div>}{answer&&<article><h3>Research answer</h3><div className="answer">{answer.answer}</div><h3>Sources ({answer.sources.length})</h3>{answer.sources.map(s=><div className="source" key={s.chunk_id}><strong>[{s.ref}] {s.filename}</strong> · {s.page?'Page '+s.page:'Text source'}<p>{s.excerpt}</p></div>)}</article>}<p className="hint">Next: geo-aware retrieval, GIS maps and policy scenarios.</p></section></main></div>
}
createRoot(document.getElementById('root')).render(<App/>);
